version: '3.2'
services:
  web:
    image: "cuppi/dd-order-proxy-api-server"
    ports:
      - "6691:8000"
    volumes:
      - ./scrapyd_jobs:/usr/src/app/jobs
  scrapyd:
    image: "cuppi/dd-order-proxy"
    ports:
      - "6800:6800"
    volumes:
      - ./scrapyd_jobs:/usr/src/app/jobs
      - ./scrapyd_logs:/usr/src/app/logs
    environment:
      SPLASH_URL: "http://splash:8050"
  splash:
    image: "scrapinghub/splash"
    ports:
      - "8050:8050"
volumes:
  scrapyd_data:
